# Generated by Django 4.2.23 on 2025-08-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_potholeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractortable',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
