# Generated by Django 4.2.23 on 2025-08-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_potholeapp', '0002_alter_contractortable_phone_alter_usertable_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logintable',
            old_name='type',
            new_name='Usertype',
        ),
    ]
