# Generated by Django 4.2.23 on 2025-09-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_potholeapp', '0003_rename_type_logintable_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
