# Generated by Django 4.2.23 on 2025-09-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_potholeapp', '0004_usertable_latitude_usertable_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertable',
            name='location',
        ),
    ]
